version: '3'

services:
  web:
    container_name: django-app
    build:
      context: .
      dockerfile: Dockerfile-django
    volumes:
      - .:/django-docker
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - postgresdb
  postgresdb:
    container_name: postgresdb
    build:
      context: .
      dockerfile: Dockerfile-postgres
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - PG_DB_PASS=password

volumes:
  postgres_data:
